version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
    - echo Install started at `date`
    - echo Current directory is `pwd`

    # Install software for API build
    - echo Installing sbt
    - wget https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.zip
    - unzip sbt-1.9.8.zip

    # Install software for frontend build
    - echo Installing frontend build dependencies
    - npm install -g create-elm-app@4.2.3 --unsafe-perm=true --allow-root

  build:
    commands:
    - echo Build started at `date`
    # test and package API
    - sbt/bin/sbt -no-colors test lambda/Universal/packageBin
    # frontend
    - cd frontend
    - elm-app build
    - cd -

  post_build:
    commands:
    - echo Deploy started at `date`
    - echo Deploying API to $FUNCTION_NAME
    - aws s3 cp lambda/target/universal/quack-stanley.zip s3://$DIST_BUCKET/$DIST_KEY
    - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $DIST_BUCKET --s3-key $DIST_KEY

    - echo Uploading static site to $WWW_BUCKET_NAME
    - cd frontend/build
    - aws s3 sync . s3://$WWW_BUCKET_NAME
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
    - cd -

artifacts:
  files:
    - target/universal/quack-stanley.zip
    - frontend/build/*
