AWSTemplateFormatVersion: 2010-09-09
Description: Persistent resources for quack-stanley application


Parameters:
  Stage:
    Type: String
    Default: prod

Resources:
  AppDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub quack-stanley-data-${Stage}
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 7
          Status: Enabled
      Tags:
      - Key: app
        Value: quack-stanley
      - Key: stage
        Value: !Ref Stage

  WebrootBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub quack-stanley-www-${Stage}
      Tags:
      - Key: app
        Value: quack-stanley
      - Key: stage
        Value: !Ref Stage
