AWSTemplateFormatVersion: 2010-09-09
Description: Create infrastructure to run Quack Stanley
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Configuration
      Parameters:
      - Stage
      - DistBucket
    - Label:
        default: Application Storage
      Parameters:
      - DataStorageBucket

Parameters:
  Stage:
    Type: String
    Description: Environment name
    Default: PROD
  DistBucket:
    Type: String
    Description: S3 Bucket that will contain the backend artifacts
  DataStorageBucket:
    Type: String
    Description: Name of the S3 bucket that will store application data

Resources:
  Backend:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub quack-stanley-${Stage}
      Description: Backend for Quack Stanley application
      CodeUri:
        Bucket: !Ref DistBucket
        Key: !Sub quack-stanley/${Stage}/quack-stanley.zip
      Handler: com.adamnfish.quackstanley.Main::handleRequest
      Runtime: java8
      Timeout: 20
      MemorySize: 512
      Environment:
        Variables:
          APP_DATA_S3_BUCKET: !Ref DataStorageBucket
          APP_STAGE: !Ref Stage
      Events:
        BackendEvent:
          Type: Api
          Properties:
            Path: /api
            Method: post
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - s3:ListBucket
          Resource: !Sub arn:aws:s3:::${DataStorageBucket}
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          Resource: !Sub arn:aws:s3:::${DataStorageBucket}/*
      Tags:
        app: quack-stanley
        stage: !Ref Stage
